# -*- coding: utf-8 -*-
"""DBWriting_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g4g_as1AtfHt3-YxOd9RZgBPOwS6mXBb
"""

#pip install psycopg2-binary

import psycopg2
import csv

engine = psycopg2.connect(
    database='postgres',
    user='postgres',
    password='riverplate1995',
    host="grupo-kvd.c7ezedheahhk.us-east-1.rds.amazonaws.com",
    port='5432'
)

#### Tabla TOPCTR ####
cursor = engine.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS base_TopCTR (advertiser_id INT PRIMARY KEY, fecha_act DATE, click INT, impression INT, rate DECIMAL);""")

with open('/TopCTR_final.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) 
    for row in reader:
        cursor.execute(
        "INSERT INTO base_TopCTR VALUES (%s, %s, %s, %s, %s)",
        row
    )
engine.commit()

cursor.execute("""select * from base_TopCTR LIMIT 5""")
rows=cursor.fetchall()
for row in rows:
  print(row)
print("Termino query")
